#bin/bash
if [[ $(which docker) && $(docker --version) ]]; then
    echo "Install docker through CLI"
     sudo apt-get update -y

       sudo apt-get install \
       apt-transport-https \
       ca-certificates \
       curl \
       gnupg-agent \
       software-properties-common
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
         sudo add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"
         sudo apt-get update -y
     sudo apt-get install docker-ce docker-ce-cli containerd.io
  else
    echo "Install docker through script"
     sudo curl -L "https://github.com/docker/compose/releases/download/1.28.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
     sudo chmod +x /usr/local/bin/docker-compose
     sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
     docker-compose --version
fi
# Up the Elastic Search through docker-compose
docker-compose  -f docker-compose.yml up -d
#health-check
sleep 30s
curl http://127.0.0.1:9200/_cat/health
root@test:/opt/docker/test# cat docker-compose.yml
version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node
